CC = iccavr
LIB = ilibw
CFLAGS =  -e -D__ICC_VERSION=722 -DATMega128  -l -g -MLongJump -MHasMul -MEnhanced -Wf-use_elpm 
ASFLAGS = $(CFLAGS) 
LFLAGS =  -g -e:0x20000 -ucrtatmega.o -bfunc_lit:0x8c.0x20000 -dram_end:0x10ff -bdata:0x100.0x10ff -dhwstk_size:384 -beeprom:0.4096 -fihx_coff -S2
FILES = main.o diskio.o ff.o delay.o sd.o gui.o zigbee.o powercheck.o usart.o SPI.o lcd.o relay.o beep.o DS18B20_driver.o ds1302.o key.o 

MASTER:	$(FILES)
	$(CC) -o MASTER $(LFLAGS) @MASTER.lk   -lfpatm128 -lcatm128
main.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
main.o:	G:\DÅÌ\LQD\software\software_src\main.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\main.c
diskio.o: .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\sd.h .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\SPI.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
diskio.o:	G:\DÅÌ\LQD\software\software_src\diskio.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\diskio.c
ff.o: .\..\software_src\ff.h .\..\software_src\integer.h .\..\software_src\ffconf.h .\..\software_src\diskio.h E:\iccv7avr\include\string.h E:\iccv7avr\include\_const.h
ff.o:	G:\DÅÌ\LQD\software\software_src\ff.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\ff.c
delay.o:
delay.o:	G:\DÅÌ\LQD\software\software_src\delay.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\delay.c
sd.o: .\..\software_src\sd.h .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
sd.o:	G:\DÅÌ\LQD\software\software_src\sd.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\sd.c
gui.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
gui.o:	G:\DÅÌ\LQD\software\software_src\gui.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\gui.c
zigbee.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
zigbee.o:	G:\DÅÌ\LQD\software\software_src\zigbee.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\zigbee.c
powercheck.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
powercheck.o:	G:\DÅÌ\LQD\software\software_src\powercheck.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\powercheck.c
usart.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
usart.o:	G:\DÅÌ\LQD\software\software_src\usart.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\usart.c
SPI.o: .\..\software_src\SPI.h .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
SPI.o:	G:\DÅÌ\LQD\software\software_src\SPI.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\SPI.c
lcd.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
lcd.o:	G:\DÅÌ\LQD\software\software_src\lcd.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\lcd.c
relay.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
relay.o:	G:\DÅÌ\LQD\software\software_src\relay.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\relay.c
beep.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
beep.o:	G:\DÅÌ\LQD\software\software_src\beep.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\beep.c
DS18B20_driver.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
DS18B20_driver.o:	G:\DÅÌ\LQD\software\software_src\DS18B20_driver.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\DS18B20_driver.c
ds1302.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
ds1302.o:	G:\DÅÌ\LQD\software\software_src\ds1302.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\ds1302.c
key.o: .\..\software_src\config.h E:\iccv7avr\include\iom128v.h E:\iccv7avr\include\stdio.h E:\iccv7avr\include\stdarg.h E:\iccv7avr\include\_const.h E:\iccv7avr\include\stdlib.h E:\iccv7avr\include\limits.h E:\iccv7avr\include\string.h E:\iccv7avr\include\macros.h E:\iccv7avr\include\AVRdef.h .\..\software_src\main.h .\..\software_src\sd.h .\..\software_src\SPI.h .\..\software_src\diskio.h .\..\software_src\integer.h .\..\software_src\ff.h .\..\software_src\ffconf.h .\..\software_src\usart.h .\..\software_src\delay.h .\..\software_src\lcd.h .\..\software_src\beep.h .\..\software_src\relay.h .\..\software_src\DS18B20_driver.h .\..\software_src\ds1302.h .\..\software_src\key.h .\..\software_src\gui.h .\..\software_src\powercheck.h .\..\software_src\zigbee.h
key.o:	G:\DÅÌ\LQD\software\software_src\key.c
	$(CC) -c $(CFLAGS) G:\DÅÌ\LQD\software\software_src\key.c
